require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserPageChecksController do

  # # This should return the minimal set of attributes required to create a valid
  # # UserPageCheck. As you add validations to UserPageCheck, be sure to
  # # adjust the attributes here as well.
  # let(:valid_attributes) { { "user_id" => "1" } }

  # # This should return the minimal set of values that should be in the session
  # # in order to pass any filters (e.g. authentication) defined in
  # # UserPageChecksController. Be sure to keep this updated too.
  # let(:valid_session) { {} }

  # describe "GET index" do
  #   it "assigns all user_page_checks as @user_page_checks" do
  #     user_page_check = UserPageCheck.create! valid_attributes
  #     get :index, {}, valid_session
  #     assigns(:user_page_checks).should eq([user_page_check])
  #   end
  # end

  # describe "GET show" do
  #   it "assigns the requested user_page_check as @user_page_check" do
  #     user_page_check = UserPageCheck.create! valid_attributes
  #     get :show, {:id => user_page_check.to_param}, valid_session
  #     assigns(:user_page_check).should eq(user_page_check)
  #   end
  # end

  # describe "GET new" do
  #   it "assigns a new user_page_check as @user_page_check" do
  #     get :new, {}, valid_session
  #     assigns(:user_page_check).should be_a_new(UserPageCheck)
  #   end
  # end

  # describe "GET edit" do
  #   it "assigns the requested user_page_check as @user_page_check" do
  #     user_page_check = UserPageCheck.create! valid_attributes
  #     get :edit, {:id => user_page_check.to_param}, valid_session
  #     assigns(:user_page_check).should eq(user_page_check)
  #   end
  # end

  # describe "POST create" do
  #   describe "with valid params" do
  #     it "creates a new UserPageCheck" do
  #       expect {
  #         post :create, {:user_page_check => valid_attributes}, valid_session
  #       }.to change(UserPageCheck, :count).by(1)
  #     end

  #     it "assigns a newly created user_page_check as @user_page_check" do
  #       post :create, {:user_page_check => valid_attributes}, valid_session
  #       assigns(:user_page_check).should be_a(UserPageCheck)
  #       assigns(:user_page_check).should be_persisted
  #     end

  #     it "redirects to the created user_page_check" do
  #       post :create, {:user_page_check => valid_attributes}, valid_session
  #       response.should redirect_to(UserPageCheck.last)
  #     end
  #   end

  #   describe "with invalid params" do
  #     it "assigns a newly created but unsaved user_page_check as @user_page_check" do
  #       # Trigger the behavior that occurs when invalid params are submitted
  #       UserPageCheck.any_instance.stub(:save).and_return(false)
  #       post :create, {:user_page_check => { "user_id" => "invalid value" }}, valid_session
  #       assigns(:user_page_check).should be_a_new(UserPageCheck)
  #     end

  #     it "re-renders the 'new' template" do
  #       # Trigger the behavior that occurs when invalid params are submitted
  #       UserPageCheck.any_instance.stub(:save).and_return(false)
  #       post :create, {:user_page_check => { "user_id" => "invalid value" }}, valid_session
  #       response.should render_template("new")
  #     end
  #   end
  # end

  # describe "PUT update" do
  #   describe "with valid params" do
  #     it "updates the requested user_page_check" do
  #       user_page_check = UserPageCheck.create! valid_attributes
  #       # Assuming there are no other user_page_checks in the database, this
  #       # specifies that the UserPageCheck created on the previous line
  #       # receives the :update_attributes message with whatever params are
  #       # submitted in the request.
  #       UserPageCheck.any_instance.should_receive(:update).with({ "user_id" => "1" })
  #       put :update, {:id => user_page_check.to_param, :user_page_check => { "user_id" => "1" }}, valid_session
  #     end

  #     it "assigns the requested user_page_check as @user_page_check" do
  #       user_page_check = UserPageCheck.create! valid_attributes
  #       put :update, {:id => user_page_check.to_param, :user_page_check => valid_attributes}, valid_session
  #       assigns(:user_page_check).should eq(user_page_check)
  #     end

  #     it "redirects to the user_page_check" do
  #       user_page_check = UserPageCheck.create! valid_attributes
  #       put :update, {:id => user_page_check.to_param, :user_page_check => valid_attributes}, valid_session
  #       response.should redirect_to(user_page_check)
  #     end
  #   end

  #   describe "with invalid params" do
  #     it "assigns the user_page_check as @user_page_check" do
  #       user_page_check = UserPageCheck.create! valid_attributes
  #       # Trigger the behavior that occurs when invalid params are submitted
  #       UserPageCheck.any_instance.stub(:save).and_return(false)
  #       put :update, {:id => user_page_check.to_param, :user_page_check => { "user_id" => "invalid value" }}, valid_session
  #       assigns(:user_page_check).should eq(user_page_check)
  #     end

  #     it "re-renders the 'edit' template" do
  #       user_page_check = UserPageCheck.create! valid_attributes
  #       # Trigger the behavior that occurs when invalid params are submitted
  #       UserPageCheck.any_instance.stub(:save).and_return(false)
  #       put :update, {:id => user_page_check.to_param, :user_page_check => { "user_id" => "invalid value" }}, valid_session
  #       response.should render_template("edit")
  #     end
  #   end
  # end

  # describe "DELETE destroy" do
  #   it "destroys the requested user_page_check" do
  #     user_page_check = UserPageCheck.create! valid_attributes
  #     expect {
  #       delete :destroy, {:id => user_page_check.to_param}, valid_session
  #     }.to change(UserPageCheck, :count).by(-1)
  #   end

  #   it "redirects to the user_page_checks list" do
  #     user_page_check = UserPageCheck.create! valid_attributes
  #     delete :destroy, {:id => user_page_check.to_param}, valid_session
  #     response.should redirect_to(user_page_checks_url)
  #   end
  # end

end
